# Uncomment the next line to define a global platform for your project
 use_frameworks!
 platform :ios, '12.0'

target 'ISLoopMeAdapter' do

  # Pods for ISLoopMeAdapter
    pod 'IronSourceSDK'
    pod 'LoopMeUnitedSDK'
end
